### ISSUE TITLE
增加一个操作

### ISSUE THREAD

**Issue by pravezhang** [zhuzhu-Top/Wx_Socket_Helper#3]
大佬，能不能帮忙增加一个操作指令？反编译汇编好难懂……

在收到笔记消息之后，笔记消息内的文件不会自动下载，需要点击打开才会，我需要抓取笔记里面的内容，能不能增加一个点击笔记消息的指令？
笔记消息长这样子：
![image](https://user-images.githubusercontent.com/41674776/125567304-b2615329-1aca-4598-b1a3-551bec32fadd.png)

点开之后是这样的
![image](https://user-images.githubusercontent.com/41674776/125567066-6b6f4685-ebb8-4a42-a21c-3d4a516570a4.png)

点开以后，微信他会自己把里面的文件下载到本地缓存文件夹，我现在只需要点开它就可以了… 方便的话可以实现一下吗。。
谢谢谢谢~

**Comment by zhuzhu-Top** [comment]
我不会为了谁专门增加什么功能，我只会做一些大部分人都需要的基础功能
